version: '2'
services:
  web:
    build: ./web
    links:
      - streamer
      - mongo
    volumes:
      - ./web:/app
    ports:
      - "4567:4567"
    command: ruby app.rb
    environment:
      - "STREAMER_URL=http://docker.local:4568"
  mongo:
    image: mongo:3.2.3
    command: "mongod --storageEngine wiredTiger"
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data
  streamer:
    build: ./streamer
    volumes:
      - ./streamer:/app
    ports:
      - "4568:4568"
    environment:
      - "HTTP_PORT=4568"
      - "TWITTER_STREAM_FILTER={ \"locations\": \"-122.75,36.8,-121.75,37.8\" }"
    env_file:
      - "secret.env"
    command: node index.js
