version: '2'
services:
  web:
    build: ./web
    links:
      - streamer
      - mongo
    volumes:
      - ./web:/app
    ports:
      - "4567:4567"
    command: ruby app.rb
    environment:
      - "STREAMER_URL=http://docker.local:4568"
    logging:
      options:
        max-size: "2k"
        max-file: "1"
  mongo:
    image: mongo:3.2.3
    command: "mongod --storageEngine wiredTiger"
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data
    logging:
      options:
        max-size: "2k"
        max-file: "1"
  streamer:
    build: ./streamer
    volumes:
      - ./streamer:/app
    ports:
      - "4568:4568"
    environment:
      - "HTTP_PORT=4568"
      - "TWITTER_STREAM_FILTER={ \"track\": \"bieber\" }"
      - "WEB_URL=http://web:4567"
    env_file:
      - "secret.env"
    command: node index.js
    logging:
      options:
        max-size: "2k"
        max-file: "1"
